### ISSUE TITLE
Downloaded Location?

### ISSUE THREAD

**Issue by MarcoPolo267** [abdellatif-laghjaj/android-all-in-one-video-downloader#12]
hii i have tried the app on OS 13, the app downloaded the video but i can nowhere find it in the storage or gallery so where its saving the videos ? Thanks

**Comment by abdellatif-laghjaj** [comment]
Hi, as u can see it's already motioned in the status, it's in your `Download/youtubedl-android`

**Comment by MarcoPolo267** [comment]
Thanks i got it now.

**Comment by MarcoPolo267** [comment]
1 last thing can the ap uploaded on the play store if we remove the youtube
download function ? will the app get suspended? Thanks

**Comment by abdellatif-laghjaj** [comment]
check the mail
