### ISSUE TITLE
YoutubeDL initialization failed

### ISSUE THREAD

**Issue by shazadanjum1** [abdellatif-laghjaj/android-all-in-one-video-downloader#3]
Hi, I have clone this repository. with this debug apk working fine but when i publish app on play store it giving error **failed to initialize**. Can you please help me to solve this problem. Thanks

**Comment by abdellatif-laghjaj** [comment]
Hello,
Can you provide more information about the issue that you've got?
Did you get it when converting it into an abb file in android studio or while publishing it on the google play console !?

Because Google play won't approve the app "50%", cuz it contains some features which it against the Youtube community standards

**Comment by shazadanjum1** [comment]
> 

I have receive a issue on play store but i resolved. now im facing issue in app. localy debug apk working fine but when i install app from play store its giving error **initialization failed: failed to initilize**  which in App.java line 35

**Comment by abdellatif-laghjaj** [comment]
Hello,
Oh, I see, The problem is in the **youtube-dl** library it seems not to be working correctly in the deployment, but still working in the debug mode.

I can't give you a fix for the **bug** at the moment, because I didn't know about this before now.

**Comment by huangShan-gitHub** [comment]
发布到谷歌商店后会初始化失败的问题，有点慌，我这个也快上架到谷歌商店了，要是碰到问题也不知道要咋整了

**Comment by abdellatif-laghjaj** [comment]
Try and see

**Comment by huangShan-gitHub** [comment]
嗯，这几天会上架，试试看了~谢谢大佬的开源

**Comment by abdellatif-laghjaj** [comment]
No need buddy,
Open source is a beautiful thing ⚡
