### ISSUE TITLE
Can i upload on play store??

### ISSUE THREAD

**Issue by arehmaan006** [abdellatif-laghjaj/android-all-in-one-video-downloader#8]
I think youtube dl library is not allowed on play store.

**Comment by abdellatif-laghjaj** [comment]
Hello,
Yeah sure you can, buf i don't know if google play will approve it or not, but just make sure to add credits.
And good luk

**Comment by arehmaan006** [comment]
Hey, can you explain how i remove youtube video downloading coding.

**Comment by abdellatif-laghjaj** [comment]
You can't remove it because it can download any video from the internet (integrated in the lib) so I guess you cant do anything about it, and it uses youtube-dl.

**Comment by arehmaan006** [comment]
Bro i think youtube dl library is banned on play store and this app downloading video by this library

**Comment by EmmanuelDav** [comment]
Unless your apps business model is to download youtube videos then sure play store will reject it, but If your app downloads other videos using youtube-dl library but prevents the download of youtube videos, Then you have no problem using the library

**Comment by arehmaan006** [comment]
If i applied a condition on youtube url than it will be work?
